### ISSUE TITLE
Readme in build references prepack which does not exist. 

### ISSUE THREAD

**Issue by galileo-chofrock** [intel/AI-Playground#103]
## Describe the bug

I am following the directions in the readme file in the build folder, but there no prepack script. 

Problem line:
> 5. Run prepack script with 3 additional arguments, this will generate `env.7z` under `WebUI\package_res` folder.
> npm run prepack <python_embed_zip> <get_pip_py> <ref_conda_env>

Scripts in my environment: 

AI-Playground\WebUI\build>npm run
Scripts available in ai-playground@1.22.1-beta via `npm run-script`:
  dev
    cross-env VITE_PLATFORM_TITLE="for Local® Dev™ Mode" vite
  pack-python
    node build\pack-python.js .\package_res
  pack-offline
    node .\build\pack-offline.js .\package_res
  prebuild
    node build\prebuild.js .\package_res ..\service .\external
  build
    npm run prebuild && npm run build:arc && npm run build:ultra && npm run build:ultra2
  build:arc
    cross-env-shell PLATFORM="arc" VITE_PLATFORM_TITLE="for Intel® Arc™" "vue-tsc && vite build && node .\build\render-template.js && electron-builder --config build\build-config.json"
  build:ultra
    cross-env-shell PLATFORM="ultra" VITE_PLATFORM_TITLE="for Intel® Core™ Ultra" "vue-tsc && vite build && node .\build\render-template.js && electron-builder --config build\build-config.json"
  build:ultra2
    cross-env-shell PLATFORM="ultra2" VITE_PLATFORM_TITLE="for Intel® Core™ Ultra Series 2" "vue-tsc && vite build && node .\build\render-template.js && electron-builder --config build\build-config.json"
  build:ultra2-offline
    cross-env-shell PLATFORM="ultra2" VITE_PLATFORM_TITLE="for Intel® Core™ Ultra Series 2" "npm run pack-offline ultra2 && npm run prebuild && vue-tsc && vite build && electron-builder --config build\build-config-offline.json"
  preview
    vite preview

## To Reproduce

Just following the directions in the readme in the build folder

## Expected behavior
Following directions should work without error. 

## Environment (please complete the following information):
- OS:  Windows11
- GPU:  Intel Arc A770 16G

**Comment by Nuullll** [comment]
Sorry, it's a typo. Fixed in https://github.com/intel/AI-Playground/commit/9729cb7227ca63f32fbd0181db030089cb869cdc
