### ISSUE TITLE
is the installer hardcoded to fetch packages from China?

### ISSUE THREAD

**Issue by greyltc** [intel/AI-Playground#126]
I'm not in China, so why is the installer (https://github.com/intel/AI-Playground/releases/download/v1.22beta/AI.Playground-1.22.1beta-Arc-dGPU_ACM.exe) fetching https://intel-optimized-pytorch.s3.cn-north-1.amazonaws.com.cn/ipex_stable/xpu/./intel_extension_for_pytorch-2.3.110.post0%2Bxpu-cp311-cp311-win_amd64.whl ?

**Comment by Nuullll** [comment]
Both `us` and `cn` are used as IPEX index url: https://github.com/intel/AI-Playground/blob/1193656f324647e8f619f40a893fdcbcb8cde69b/service/requirements-arc.txt#L4-L5

The `us` site was down: https://github.com/intel/intel-extension-for-pytorch/issues/745, so it might fallback to `cn` site.

**Comment by greyltc** [comment]
That explains it! Thanks.

Don't know if It's easy to add a european or other endpoints for robustness, but it might be worth considering. I guess neither China nor US is a great option if one is installing from europe.
