### ISSUE TITLE
Backend could not generate image

### ISSUE THREAD

**Issue by CraterCrater** [intel/AI-Playground#130]
## Describe the bug

When attempting to generate an image using the workflow option I receive an error message of "Backend could not generate image
I wonder if it is connected to this?
[comfyui-backend]: invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node UnetLoaderGGUF does not exist.', 'details': "Node ID '#170'", 'extra_info': {}}

## To Reproduce

Click on create tab
go to settings
go to workflow under mode
select either flux workflow
then type a prompt 

## Expected behavior
I expected an image to be generate but instead received the above message, below is my log from that 

## Screenshots

[ai-backend]: Stopping backend ai-backend. It was in state running
[ai-backend]: encountered unexpected exit in ai-backend.
[ai-backend]:  trying to start ai-backend python API
[ai-backend]: Setting device selector to level_zero:0
[ai-backend]: C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ai-backend-env\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ai-backend-env\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

[ai-backend]: C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ai-backend-env\Lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(

[ai-backend]: 2024-12-20 11:11:21,144 - INFO - intel_extension_for_pytorch auto imported

[ai-backend]: workarounds applied
 * Serving Flask app 'web_api'
 * Debug mode: off

[ai-backend]: 2024-12-20 11:11:26,453 - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:59000

[ai-backend]: 2024-12-20 11:11:26,453 - INFO - Press CTRL+C to quit

[ai-backend]: 2024-12-20 11:11:26,571 - INFO - 127.0.0.1 - - [20/Dec/2024 11:11:26] "GET /healthy HTTP/1.1" 200 -

[ai-backend]: received response: 200
[ai-backend]: ai-backend server startup complete after 9.613259200000087 seconds
[ai-backend]: started server ai-backend on http://127.0.0.1:59000
[ai-backend]: 2024-12-20 11:11:26,576 - INFO - 127.0.0.1 - - [20/Dec/2024 11:11:26] "POST /api/comfyUi/installPythonPackage HTTP/1.1" 200 -

[ai-backend]: 2024-12-20 11:11:26,589 - INFO - custom node installation request result: []

[ai-backend]: 2024-12-20 11:11:26,590 - INFO - 127.0.0.1 - - [20/Dec/2024 11:11:26] "POST /api/comfyUi/loadCustomNodes HTTP/1.1" 200 -

[comfyui-backend]: got prompt

[comfyui-backend]: invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node UnetLoaderGGUF does not exist.', 'details': "Node ID '#170'", 'extra_info': {}}

[ai-backend]: 2024-12-20 11:11:34,398 - INFO - 127.0.0.1 - - [20/Dec/2024 11:11:34] "GET / HTTP/1.1" 404 -

## Environment (please complete the following information):

- OS: Windows 11 
- GPU: Intel Arc A770 16G - Acer
- CPU: i9- 10850K
- Version: 2.0.0-alpha-preview

**Comment by CraterCrater** [comment]
However I am able to run flux in the ComfyUI directly, so that is very nice!

**Comment by CraterCrater** [comment]
I have been rebooting and trying various things, I noticed the below when I ran the program again:

[comfyui-backend]: [Prompt Server] web root: C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\web

[comfyui-backend]: Traceback (most recent call last):
  File "C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\nodes.py", line 2070, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-GGUF\__init__.py", line 7, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 3, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'

Cannot import C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-GGUF module for custom nodes: No module named 'gguf'

[comfyui-backend]:
Import times for custom nodes:
   0.0 seconds: C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\websocket_image_save.py

[comfyui-backend]:    0.0 seconds (IMPORT FAILED): C:\Users\rober\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-GGUF


[comfyui-backend]: Starting server


[comfyui-backend]: To see the GUI go to: http://127.0.0.1:49000

[comfyui-backend]: received response: 200
[comfyui-backend]: comfyui-backend server startup complete after 5.417712 seconds
[comfyui-backend]: started server comfyui-backend on http://127.0.0.1:49000

**Comment by qiacheng** [comment]
looks like the custom node installation failed and it's missing gguf module in the comfyui env.

1. try reinstalling comfyui backend in the backend manager

2. if it doesn't work, try the following:

open cmd

cd to AI Playground install location, in your case

`cd C:\Users\rober\AppData\Local\Programs\AI Playground\resources`

`.\comfyui-backend-env\python.exe -m pip install gguf`

restart AI Playground and re run the Flux workflow.

also we could access comfyUI after AI Playground is launched by going to http://127.0.0.1:49000/

**Comment by CraterCrater** [comment]
I installed it manually with your instructions and that solved the problem! Thanks!
