### ISSUE TITLE
AI Playground Answer error

### ISSUE THREAD

**Issue by Gydvins** [intel/AI-Playground#20]
![AI chat answer 2024-08-04 ](https://github.com/user-attachments/assets/26ead94b-1a60-408f-8825-a5d004f431fd)

**Comment by Gydvins** [comment]
Characteristics 
MEDION ERAZER® Major X10, Gaming Notebook, 16 Display, Intel® Core™ i7,i7-12700H Prozessor, 16 GB RAM, 1 TB SSD, NVIDIA Arc™ 7 A730M, , Windows 11 Home (64 Bit)

**Comment by qiacheng** [comment]
does image generation work? We found an issue with the v1.0b installer where some of the packages are expired on Pypi, so it wasn't getting installed properly.

**Comment by bobduffy** [comment]
> ![AI chat answer 2024-08-04 ](https://private-user-images.githubusercontent.com/177461526/354902055-26ead94b-1a60-408f-8825-a5d004f431fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzU2MDQsIm5iZiI6MTcyMzIzNTMwNCwicGF0aCI6Ii8xNzc0NjE1MjYvMzU0OTAyMDU1LTI2ZWFkOTRiLTFhNjAtNDA4Zi04ODI1LWE1ZDAwNGY0MzFmZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQyMDI4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODhiZDUwZmYxY2U3ZDFjYjQ3NWQzNGMwYTBkMGIyN2JkZGIzNTA1MTNmMWU5M2QyYjIxOTljNWZlZDEzYzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SAKdFHp86PernK0yFRdm6QOARGTqKnljhnVQ6eXsJEs)

Try version 1.01b   Should fix this

**Comment by aloa7** [comment]
Same problem here, both in image creation and in answer. In both I receive the same error as the image in the first post as a response
Version installed:  AI.Playground-v1.01b-Desktop_dGPU 

My specifications:
i5 14500
ARC A770
32GB DDR5
1TB SSD + 2TB SSD
Windows 11 Pro

**Comment by Gydvins** [comment]
@bobduffy Thanks for your recommendations.
