### ISSUE TITLE
Stuck on loading, unable to load successfully

### ISSUE THREAD

**Issue by fengjietang** [intel/AI-Playground#26]
After installing "AI Playground for Desktop-dGPU," when you click to run "AI Playground," it remains stuck on Loading and is unusable
![2382d455d2c0071385288c4b65e679d](https://github.com/user-attachments/assets/acec435f-4935-4713-b4aa-19ac0f65fa2f)

**Comment by slippystance** [comment]
Encountering the same issue.  This is linked to an issue with a blocked port.  As of this build, I'm seeing port "59999" coming up as blocked when using debug.

This is an ongoing issue with no easy workaround, yes?

(Win11/ArcA770 16gb)

**Comment by silversoul98** [comment]
I'm having this same problem. Port 9999 in the debug console. According to the post in the Discord channel, a fix is in the dev branch, as of 7/26/24

**Comment by thatmemory** [comment]
> the latest v1.01b installer allows port change.
> 
> install the v1.01b version.. navigate to ai playground install location and open resources/settings.json
> 
> "envType":"Arc", "port":"8808",
> 
> save and relaunch
> 
> now the backend service port should be changed to 8808

I tried it.now I can't open this app again. The task manager said it running, however, nothing happened.

**Comment by slippystance** [comment]
> > the latest v1.01b installer allows port change.
> > install the v1.01b version.. navigate to ai playground install location and open resources/settings.json
> > "envType":"Arc", "port":"8808",
> > save and relaunch
> > now the backend service port should be changed to 8808
> 
> I tried it.now I can't open this app again. The task manager said it running, however, nothing happened.

![image](https://github.com/user-attachments/assets/04e03d5b-cb07-4c48-bf1d-04b2800e81d0)

Is what I'm seeing.

**Comment by qiacheng** [comment]
@slippystance the console in the screenshot above is for front end, do you see a command prompt window?

if not, then it could be that the cmd crashed at startup due to env issues.

Could you do the following:

1. open a command prompt
2. cd to ai playground install location\resources\service
3. 
![image](https://github.com/user-attachments/assets/8af63e2c-8f3e-4159-85a8-2f373a69c2f1)


4. type in `..\env\python.exe web_api.py`
5. 
![image](https://github.com/user-attachments/assets/fccc8108-41e3-4f89-979a-98e2e2f53278)


if you see similar logs as the screenshot shown above, then the setup is correct. Further triage is needed

**Comment by slippystance** [comment]
> @slippystance the console in the screenshot above is for front end, do you see a command prompt window?
> 
> if not, then it could be that the cmd crashed at startup due to env issues.
> 
> Could you do the following:
> 
>     1. open a command prompt
> 
>     2. cd to ai playground install location\resources\service
> 
> 
> ![image](https://private-user-images.githubusercontent.com/25306710/356690944-8af63e2c-8f3e-4159-85a8-2f373a69c2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjM1NzAsIm5iZiI6MTcyMzIyMzI3MCwicGF0aCI6Ii8yNTMwNjcxMC8zNTY2OTA5NDQtOGFmNjNlMmMtOGYzZS00MTU5LTg1YTgtMmYzNzNhNjljMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTk3MGFiOTA4Y2ExOGQ4ZmUyMzg3NmI3Njg1Mzk0Njc1OTgxZTllZTRjNTI0YmJmNjA4YjNjNDk1NmM3ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GTqkoRrFlM-_Y1zWgpgUWiEY1OzOefCxSkCtJL_1RU)
> 
>     4. type in `..\env\python.exe web_api.py`
> 
> 
> ![image](https://private-user-images.githubusercontent.com/25306710/356691172-fccc8108-41e3-4f89-979a-98e2e2f53278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjM1NzAsIm5iZiI6MTcyMzIyMzI3MCwicGF0aCI6Ii8yNTMwNjcxMC8zNTY2OTExNzItZmNjYzgxMDgtNDFlMy00Zjg5LTk3OWEtOThlMmUyZjUzMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOTUwMTE3ZGI3MGYxY2U0MzA1NDAxMzllMTg3ZTJiNmU2MGNjOTg5NmMwNGY2MjgzMGU5MmQyMThhOTZhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bYZ0hNUHnliw4GpI3-Pth-hdYzBHssQzl6_y5ihqgkk)
> 
> if you see similar logs as the screenshot shown above, then the setup is correct. Further triage is needed
This is what I'm seeing:

![image](https://github.com/user-attachments/assets/4241af04-5fd3-4bc1-84a7-0fa53f95ac65)

**Comment by qiacheng** [comment]
could you try installing VS C++ redist from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 

and re run above command again?

**Comment by slippystance** [comment]
This seems to have gotten the app to launch and it's now downloading models.
![image](https://github.com/user-attachments/assets/09097335-255d-4c6b-ac11-e49c621f9c09)

Specifically, I used the X64 redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by bobduffy** [comment]
Added VS C++ workaround to the readme and release notes

**Comment by fengjietang** [comment]
> > could you try installing VS C++ redist from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
> > and re run above command again?
> 
> That's worked. Cyber doctor.❤

Thank you for your response. However, even after installing vc_redist.x64.exe, it still doesn't work.

**Comment by fengjietang** [comment]
> Added VS C++ workaround to the readme and release notes

Thank you for your response. However, even after installing vc_redist.x64.exe, it still doesn't work.

**Comment by thatmemory** [comment]
> > 在自述文件和发行说明中添加了 VS C++ 解决方法
> 
> 谢谢你的回复。但是，即使安装了 vc_redist.x64.exe，它仍然不起作用。

I don't konw,maybe you should uninstall it and try again.

**Comment by fengjietang** [comment]
> > > 在自述文件和发行说明中添加了 VS C++ 解决方法
> > 
> > 
> > 谢谢你的回复。但是，即使安装了 vc_redist.x64.exe，它仍然不起作用。
> 
> I don't konw,maybe you should uninstall it and try again.

After uninstalling and reinstalling, the issue has been resolved
