### ISSUE TITLE
A380 - Compatible or not ?

### ISSUE THREAD

**Issue by NikosDi** [intel/AI-Playground#4]
Hello.
I have an Intel Core i7 with Intel ARC A380 gpu - latest drivers using Windows 11

The program installed and is running without issues - only painfully slow at the beginning where it stuck for several minutes at "Generating..." using only two threads of the CPU, when I asked for an image at standard resolution (512x512) and standard quality with the default settings

Then it took me a lot of time to generate the first image, using again the CPU only.

But after that, it finally started to leverage the A380 and the app is fast enough to produce images at default (standard) settings.

1) So, how strict is the requirement of 8GB VRAM when the app is running without issues on a A380 using 6GB VRAM ?

2) Are there any limitations or quality differences using the 6GB VRAM of A380 versus the 8GB of minimum VRAM ?

Thank you

**Comment by qiacheng** [comment]
the current version doesn't have AOT IPEX compiled for A380, so the first time it tries to generate the image it will JIT compile those required kernels. (That's the reason why it took alot of time to generate for the first image, then the following operations will be fast in create/enhance tab, switching models etc, until you restart the app)

8GB+ VRAM is recommended as we have tested it across features, but in the future we can look into getting it more optimized so Arc GPUs with lower VRAM would have better UX. You are welcome to contribute to the repo :)

There is no image quality differences using 6GB VRAM, it's just that the image generation time and UX will get impacted

Hope this helps

**Comment by NikosDi** [comment]
Unfortunately I'm not a developer, just an IT guy :)

I have already tried the guide from here https://github.com/openvinotoolkit/stable-diffusion-webui/wiki/Installation-on-Intel-Silicon in order to run Automatic1111 using OpenVINO on Arc cards and A380 works like a charm.

But I haven't experimented a lot with features other than basics.

Anyway, I haven't tried to open and close the app to see the delay again - that would be a major drawback for A380 users.

Waiting for your next version with optimizations for entry level GPUs too - I hope so :)

TY
