### ISSUE TITLE
hang on "npm install"

### ISSUE THREAD

**Issue by cboss6** [intel/AI-Playground#61]
## Describe the bug

I tried to enable development environment, and when I doing the step in [npm install](https://github.com/intel/AI-Playground#webui-nodejs--electron), the cmd will hang without any output, see my screen shot below.

## To Reproduce
follow https://github.com/intel/AI-Playground#webui-nodejs--electron

## Screenshots
![image](https://github.com/user-attachments/assets/f8c9fc19-4d39-4a77-a907-2cc90876190c)

## Environment (please complete the following information):
- OS: [Windows11]
- GPU: [Intel Arc A770 16G]
- CPU: [Intel(R) Core(TM) Ultra 5 238V]

**Comment by Nuullll** [comment]
@cboss6 It's probably a network issue. Did you setup proxy in your environment?
