### ISSUE TITLE
virus in the "AI Playground for Desktop-dGPU (ACM)" file

### ISSUE THREAD

**Issue by Sitarani1978** [intel/AI-Playground#63]
## Describe the bug

There is malware in the file "AI Playground for Desktop-dGPU (ACM)" and can affect the system.

## Expected behavior

The download and installation should occur without any error, and when I download the file, I get an error from antivirus software installed in my system.

## Screenshots

![image](https://github.com/user-attachments/assets/65487f7d-3754-4e4f-88ed-ae99a5887e52)

## Environment (please complete the following information):

- OS: Windows11
CPU: i7-13650HX

**Comment by Nuullll** [comment]
Feel like a false alarm. The flagged URL is from GitHub.

**Comment by Sitarani1978** [comment]
I had downloaded the file, and my antivirus software (McAfee) gave me the notification that a virus was found in this file.

**Comment by Sitarani1978** [comment]
I had downloaded the file, and my antivirus software (McAfee) gave me the notification that a virus was found in this file.

**Comment by orion14794** [comment]
I tried downloading it and Windows Defender gave me a virus warning and stopped the download process. Virus named "Trojan:Script/Wacatac.B!ml". https://codeload.github.com/intel/AI-Playground/zip/refs/heads/main|pid:15952,ProcessStart:133785477033041453
