### ISSUE TITLE
So, is there no more updates for the Ultra 1 chip?

### ISSUE THREAD

**Issue by brownplayer** [intel/AI-Playground#72]

**Comment by Nuullll** [comment]
We'll have updates for all platforms, right now we are resolving the final issues for Ultra 1, stay tuned.

**Comment by mistann** [comment]
> We'll have updates for all platforms, right now we are resolving the final issues for Ultra 1, stay tuned.

Great to hear! Eagerly awaiting for an  update for the Ultra 1 chip also!
