### ISSUE TITLE
Need to disable integrated GPU when using A770

### ISSUE THREAD

**Issue by rajpatel9498** [intel/AI-Playground#79]
## Describe the bug

My machine has i7-13700K CPU with iGPU as Intel UHD Graphics 770 and dGPU as Intel Arc 770 (8 GB). When trying to run following command to check whether the XPU environment is correct or not, running into an error which says PI_ERROR_INVALID_DEVICE.

`python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"`

## To Reproduce

1. Machine with iGPU enabled + Arc 770 (8 GB)

## Expected behavior

XPU environment should be detected correct

## Screenshots

The error log is as following:
`C:\Users\Raj Patel\.conda\envs\aipc_xpu\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\Raj Patel\.conda\envs\aipc_xpu\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from torchvision.io, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have libjpeg or libpng installed before building torchvision from source?
  warn(
2.3.1+cxx11.abi
2.3.110+xpu
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Raj Patel\.conda\envs\aipc_xpu\lib\site-packages\torch\xpu\__init__.py", line 57, in device_count
    return torch._C._xpu_getDeviceCount()
RuntimeError: Can't add devices across platforms to a single context. -33 (PI_ERROR_INVALID_DEVICE)
(aipc_xpu) `

## Environment (please complete the following information):

- OS: Windows11 24H2
- dGPU: [Intel Arc A770 8GB]
- iGPU: [UHD Graphics 770]
- CPU: [i7-13700K]
- Version: Tip of the dev branch [2486734](https://github.com/intel/AI-Playground/tree/24867340d71d4982cbe8d803f8df644fe4c14828)

## Additional context

**I was able to fix this issue by disabling iGPU device from Windows Device manager.**

**Comment by Nuullll** [comment]
Duplicated with https://github.com/intel/AI-Playground/issues/76 and https://github.com/intel/intel-extension-for-pytorch/issues/718

**Comment by cf418** [comment]
I have the same issue. A workaround for me was to set the environment variable set ONEAPI_DEVICE_SELECTOR=*:<id of dgpu> to prevent the iGPU from being seen.
