### ISSUE TITLE
Will not pass loading screen, torchvision issue

### ISSUE THREAD

**Issue by Jamesrggg** [intel/AI-Playground#85]
Hello! I'm having the issue where AI playground will not go mast the loading screen. I was able to make it work my first day but the next day and today it has stopped working. Here is what I have tried.

- All my drivers are up-to-date
- Reinstalled both Microsoft Visual C++ Redistributable versions
- Reinstalled AI playground.

Here is the error I find:
PS C:\Users\james\AppData\Local\Programs\AI Playground\resources\service> ..\env\python.exe .\web_api.py
C:\Users\james\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\james\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from torchvision.io, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have libjpeg or libpng installed before building torchvision from source?
warn(
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path:
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll

Any help would be greatly appreciated, thank you for your time!

**Comment by Nuullll** [comment]
@Jamesrggg can you please execute `..\env\python.exe -m pip list` and post the log?

**Comment by Jamesrggg** [comment]
> ..\env\python.exe -m pip list

PS C:\Users\james\AppData\Local\Programs\AI Playground\resources\service> ..\env\python.exe -m pip list
Package                     Version
--------------------------- ----------------------
absl-py                     2.1.0
accelerate                  1.1.0
addict                      2.4.0
aiohappyeyeballs            2.4.3
aiohttp                     3.10.10
aiosignal                   1.3.1
annotated-types             0.7.0
anyio                       4.6.2.post1
attrs                       24.2.0
backoff                     2.2.1
basicsr                     1.4.2
beautifulsoup4              4.12.3
bigdl-core-xe-21            2.5.0b20240715
bigdl-core-xe-addons-21     2.5.0b20240715
bigdl-core-xe-batch-21      2.5.0b20240715
blinker                     1.8.2
certifi                     2024.8.30
cffi                        1.17.1
chardet                     5.2.0
charset-normalizer          3.4.0
click                       8.1.7
colorama                    0.4.6
compel                      2.0.2
cryptography                43.0.3
dataclasses-json            0.6.7
datasets                    2.18.0
diffusers                   0.27.2
dill                        0.3.8
docstring_parser            0.16
docx2txt                    0.8
emoji                       2.14.0
eval_type_backport          0.2.0
faiss-cpu                   1.8.0
filelock                    3.16.1
filetype                    1.2.0
Flask                       3.0.3
frozenlist                  1.5.0
fsspec                      2024.2.0
future                      1.0.0
greenlet                    3.1.1
grpcio                      1.67.1
h11                         0.14.0
httpcore                    1.0.6
httpx                       0.27.2
huggingface-hub             0.25.2
idna                        3.10
imageio                     2.36.0
importlib_metadata          8.5.0
intel_extension_for_pytorch 2.1.40+xpu
ipex-llm                    2.1.0b20240715
itsdangerous                2.2.0
Jinja2                      3.1.4
joblib                      1.4.2
jsonpatch                   1.33
jsonpath-python             1.0.6
jsonpointer                 3.0.0
langchain                   0.2.11
langchain-community         0.2.10
langchain-core              0.2.23
langchain-text-splitters    0.2.4
langdetect                  1.0.9
langsmith                   0.1.139
lazy_loader                 0.4
lmdb                        1.5.1
lxml                        5.3.0
Markdown                    3.7
markdown-it-py              3.0.0
MarkupSafe                  3.0.2
marshmallow                 3.23.1
mdurl                       0.1.2
mpmath                      1.3.0
multidict                   6.1.0
multiprocess                0.70.16
mypy-extensions             1.0.0
nest-asyncio                1.6.0
networkx                    3.4.2
nltk                        3.9.1
numpy                       1.26.4
opencv-python               4.9.0.80
orjson                      3.10.11
packaging                   24.1
pandas                      2.2.3
peft                        0.10.0
pillow                      10.3.0
pip                         24.3.1
platformdirs                4.3.6
propcache                   0.2.0
protobuf                    5.28.3
psutil                      5.9.8
pyarrow                     18.0.0
pyarrow-hotfix              0.6
pycparser                   2.22
pydantic                    2.9.2
pydantic_core               2.23.4
Pygments                    2.18.0
pyparsing                   3.2.0
pypdf                       4.2.0
python-dateutil             2.8.2
python-iso639               2024.10.22
python-magic                0.4.27
pytz                        2024.2
PyYAML                      6.0.2
RapidFuzz                   3.10.1
regex                       2024.9.11
requests                    2.32.3
requests-toolbelt           1.0.0
rich                        13.9.4
safetensors                 0.4.5
scikit-image                0.24.0
scikit-learn                1.5.2
scipy                       1.14.1
sentence-transformers       2.3.1
sentencepiece               0.2.0
setuptools                  69.5.1
shtab                       1.7.1
six                         1.16.0
sniffio                     1.3.1
soupsieve                   2.6
SQLAlchemy                  2.0.36
sympy                       1.13.3
tabulate                    0.9.0
tb-nightly                  2.19.0a20241103
tenacity                    8.5.0
tensorboard-data-server     0.7.2
threadpoolctl               3.5.0
tifffile                    2024.9.20
tokenizers                  0.15.2
tomli                       2.0.2
torch                       2.1.0.post3+cxx11.abi
torchvision                 0.16.0.post3+cxx11.abi
tqdm                        4.66.6
transformers                4.39.0
trl                         0.9.3
typing_extensions           4.12.2
typing-inspect              0.9.0
tyro                        0.8.14
tzdata                      2024.2
unstructured                0.14.6
unstructured-client         0.26.2
urllib3                     2.2.3
Werkzeug                    3.1.1
wheel                       0.43.0
wrapt                       1.16.0
xxhash                      3.5.0
yapf                        0.40.2
yarl                        1.17.1
zipp                        3.20.2

**Comment by Nuullll** [comment]
It seems `dpcpp-cpp-rt` and `mkl-dpcpp` are missing in your python environment.

Try this:
```..\env\python.exe -m pip install dpcpp-cpp-rt==2024.2.1 mkl-dpcpp==2024.2.1```

**Comment by Jamesrggg** [comment]
I have gotten them added but the issue persists 

absl-py                     2.1.0
accelerate                  1.1.0
addict                      2.4.0
aiohappyeyeballs            2.4.3
aiohttp                     3.10.10
aiosignal                   1.3.1
annotated-types             0.7.0
anyio                       4.6.2.post1
attrs                       24.2.0
backoff                     2.2.1
basicsr                     1.4.2
beautifulsoup4              4.12.3
bigdl-core-xe-21            2.5.0b20240715
bigdl-core-xe-addons-21     2.5.0b20240715
bigdl-core-xe-batch-21      2.5.0b20240715
blinker                     1.8.2
certifi                     2024.8.30
cffi                        1.17.1
chardet                     5.2.0
charset-normalizer          3.4.0
click                       8.1.7
colorama                    0.4.6
compel                      2.0.2
cryptography                43.0.3
dataclasses-json            0.6.7
datasets                    2.18.0
diffusers                   0.27.2
dill                        0.3.8
docstring_parser            0.16
docx2txt                    0.8
dpcpp-cpp-rt                2024.2.1
emoji                       2.14.0
eval_type_backport          0.2.0
faiss-cpu                   1.8.0
filelock                    3.16.1
filetype                    1.2.0
Flask                       3.0.3
frozenlist                  1.5.0
fsspec                      2024.2.0
future                      1.0.0
greenlet                    3.1.1
grpcio                      1.67.1
h11                         0.14.0
httpcore                    1.0.6
httpx                       0.27.2
huggingface-hub             0.25.0
idna                        3.10
imageio                     2.36.0
importlib_metadata          8.5.0
intel-cmplr-lib-rt          2024.2.1
intel-cmplr-lib-ur          2024.2.1
intel-cmplr-lic-rt          2024.2.1
intel_extension_for_pytorch 2.1.40+xpu
intel-opencl-rt             2024.2.1
intel-openmp                2024.2.1
intel-sycl-rt               2024.2.1
ipex-llm                    2.1.0b20240715
itsdangerous                2.2.0
Jinja2                      3.1.4
joblib                      1.4.2
jsonpatch                   1.33
jsonpath-python             1.0.6
jsonpointer                 3.0.0
langchain                   0.2.11
langchain-community         0.2.10
langchain-core              0.2.23
langchain-text-splitters    0.2.4
langdetect                  1.0.9
langsmith                   0.1.139
lazy_loader                 0.4
lmdb                        1.5.1
lxml                        5.3.0
Markdown                    3.7
markdown-it-py              3.0.0
MarkupSafe                  3.0.2
marshmallow                 3.23.1
mdurl                       0.1.2
mkl                         2024.2.1
mkl-dpcpp                   2024.2.1
mpmath                      1.3.0
multidict                   6.1.0
multiprocess                0.70.16
mypy-extensions             1.0.0
nest-asyncio                1.6.0
networkx                    3.4.2
nltk                        3.9.1
numpy                       1.26.4
onemkl-sycl-blas            2024.2.1
onemkl-sycl-datafitting     2024.2.1
onemkl-sycl-dft             2024.2.1
onemkl-sycl-lapack          2024.2.1
onemkl-sycl-rng             2024.2.1
onemkl-sycl-sparse          2024.2.1
onemkl-sycl-stats           2024.2.1
onemkl-sycl-vm              2024.2.1
opencv-python               4.9.0.80
orjson                      3.10.11
packaging                   24.1
pandas                      2.2.3
peft                        0.10.0
pillow                      10.3.0
pip                         24.3.1
platformdirs                4.3.6
propcache                   0.2.0
protobuf                    5.28.3
psutil                      5.9.8
pyarrow                     18.0.0
pyarrow-hotfix              0.6
pycparser                   2.22
pydantic                    2.9.2
pydantic_core               2.23.4
Pygments                    2.18.0
pyparsing                   3.2.0
pypdf                       4.2.0
python-dateutil             2.8.2
python-iso639               2024.10.22
python-magic                0.4.27
pytz                        2024.2
PyYAML                      6.0.2
RapidFuzz                   3.10.1
regex                       2024.9.11
requests                    2.32.3
requests-toolbelt           1.0.0
rich                        13.9.4
safetensors                 0.4.5
scikit-image                0.24.0
scikit-learn                1.5.2
scipy                       1.14.1
sentence-transformers       2.3.1
sentencepiece               0.2.0
setuptools                  69.5.1
shtab                       1.7.1
six                         1.16.0
sniffio                     1.3.1
soupsieve                   2.6
SQLAlchemy                  2.0.36
sympy                       1.13.3
tabulate                    0.9.0
tb-nightly                  2.19.0a20241103
tbb                         2021.13.1
tenacity                    8.5.0
tensorboard-data-server     0.7.2
threadpoolctl               3.5.0
tifffile                    2024.9.20
tokenizers                  0.15.2
tomli                       2.0.2
torch                       2.1.0.post3+cxx11.abi
torchvision                 0.16.0.post3+cxx11.abi
tqdm                        4.66.6
transformers                4.39.0
trl                         0.9.3
typing_extensions           4.12.2
typing-inspect              0.9.0
tyro                        0.8.14
tzdata                      2024.2
unstructured                0.14.6
unstructured-client         0.26.2
urllib3                     2.2.3
Werkzeug                    3.1.1
wheel                       0.43.0
wrapt                       1.16.0
xxhash                      3.5.0
yapf                        0.40.2
yarl                        1.17.1
zipp                        3.20.2

**Comment by Nuullll** [comment]
Is this the full log? The torchvision message is a harmless warning which you can ignore. 
```
PS C:\Users\james\AppData\Local\Programs\AI Playground\resources\service> ..\env\python.exe .\web_api.py
C:\Users\james\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\james\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from torchvision.io, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have libjpeg or libpng installed before building torchvision from source?
warn(
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path:
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll
```

**Comment by Nuullll** [comment]
And what's your driver version?

**Comment by Jamesrggg** [comment]
32.0.101.6130, I did a clean reinstall of it and its working well now. Thank you!
