### ISSUE TITLE
Backend initialization failed - ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by Undervolted-c** [intel/AI-Playground#93]
## Describe the bug

The AI inference backend failed to initialize. 
Please try restarting the application. 
If the problem persists, you can check the Details for additional information about the error.

from flask import Flask, jsonify, request, Response, stream_with_context
ModuleNotFoundError: No module named 'flask'

## Screenshots :

![image](https://github.com/user-attachments/assets/5e84fd59-4555-4279-aff0-66f33e5906f6)

Log : 

![image](https://github.com/user-attachments/assets/23df6eea-a649-4a1f-95dc-ff5d0abac6fd)

![image](https://github.com/user-attachments/assets/6e603a26-55f4-4356-b378-902435d83d79)

## Environment :

- OS: Win11
- GPU: Arc A770LE 16GB
- CPU: i7 14700
- Version: v1.22.1-b

## Python 3.12
Pip list : 
> flask 3.0.3 > checked
> pip 24.3.1 > checked

**Comment by Nuullll** [comment]
Broken python environment during installation. You can follow these steps to recover:
1. Open a terminal under `<InstallDir>\resources\service\`
2. Execute `..\env\python.exe -m pip install -r .\requirements-arc.txt`
