### ISSUE TITLE
Backend Initialization falled. ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by brainai-hub** [intel/AI-Playground#96]
Dear, 

I have some great news! 
The new version has fixed the "loading forever" error. 
I downloaded the new installer program, specifically the Installer for Intel Core Ultra-H Processors, as my AI PC is an Ultra 5 model.

However, I encountered the following error:

![image](https://github.com/user-attachments/assets/fb36533a-e4d2-4097-8f28-267c536742ad)

![image](https://github.com/user-attachments/assets/9702ad12-f668-40a9-bed5-22af73bb4eb7)

Here is my NPU and CPU information:

![image](https://github.com/user-attachments/assets/1c76b558-6462-4dba-8175-9e8775527a57)

![image](https://github.com/user-attachments/assets/36f9b624-80bc-40f7-adba-951ca5b7e21a)

After following trouble shooting Installation steps. 
![image](https://github.com/user-attachments/assets/66b1ff11-fb3c-43e5-9749-7fc5d917f4da)

There is no more error detail. but I still can't open the AI Playground program.
![image](https://github.com/user-attachments/assets/435c7671-7f8a-4e42-a446-4b38c5b007e2)

Can anyone help me resolve this issue?

Thank you!

**Comment by Nuullll** [comment]
Seems duplicated with https://github.com/intel/AI-Playground/issues/93

> Broken python environment during installation. You can follow these steps to recover:
> 1. Open a terminal under `<InstallDir>\resources\service\`
> 2. Execute `..\env\python.exe -m pip install -r .\requirements-arc.txt`

**Comment by brainai-hub** [comment]
![image](https://github.com/user-attachments/assets/11641375-01ed-4dde-bb95-96e8d46cf70e)


![image](https://github.com/user-attachments/assets/3414ebe0-f1c3-43ba-b59b-8563d1b20e55)

**Comment by brainai-hub** [comment]
![image](https://github.com/user-attachments/assets/f91a4c53-dc5d-4d50-b054-53df07082150)

**Comment by brainai-hub** [comment]
![image](https://github.com/user-attachments/assets/8eb6eebf-7d78-437d-beb6-46a69f4b7720)

**Comment by brainai-hub** [comment]
![image](https://github.com/user-attachments/assets/4b9fbed2-f76a-4c2b-92a7-ed2bb1197553)

**Comment by brainai-hub** [comment]
![image](https://github.com/user-attachments/assets/76bf1b03-4f01-4eae-99b2-690dfe04047f)

**Comment by Nuullll** [comment]
It seems you have problems with your network. Could you please try to open `<InstallDir>\resources\service\requirements-arc.txt` and **remove** the following line:
```
--extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/
```

And then retry https://github.com/intel/AI-Playground/issues/96#issuecomment-2473529362

**Comment by brainai-hub** [comment]
You were right. I reinstalled the program in a strong network environment, and it works now.
Thank you!
